#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d sys term www dev txt vid flt spot virt gfx

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false
bspc config single_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Alacritty desktop='^2'
bspc rule -a firefox desktop='^3'
# bspc rule -a Geany desktop='^9'
bspc rule -a Spotify desktop='^8'
bspc rule -a virt-manager desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#ed8796"
bspc config normal_border_color         "#8AADF4"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar
killall polybar &
zsh ~/.config/polybar/launch.sh &

# Notifications
pkill screen_msg.sh &
~/.config/scripts/screen_msg.sh &
/usr/bin/dunst &

# Conky
killall -q conky
while pgrep -u $UID -x conky >/dev/null; do sleep 1; done &
conky -c ~/.config/conky.conf &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &

# Picom
picom -b &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
